
import  { ArticleDescription } from './types/ArticleDescription'

import Edito from './articles/Editorial/description'
import BK from './articles/Benharira_Koeppel/description'
import BC from './articles/Boyer_Ciavaldini/description'
import BL from './articles/Brami_Labendzki/description'
import CS from './articles/Chassignet_Salanon/description'
import CL from './articles/Chikar_Lafontaine/description'
import DD from './articles/Daigmorte_DeSmet/description'
import Du from './articles/Dumoulin/description'
import DG from './articles/Durand_Gaillot/description'
import Fo from './articles/Fouchy/description'
import GJ from './articles/Geslin_Julien/description'
import Ha from './articles/Haerinck/description'
import HG from './articles/Haudegond_Guyonneau/description'
import KB from './articles/Kohlmuller_Boyer/description'
import La from './articles/Lagier/description'
import LL from './articles/Lassare_Lesbats/description'
import Li from './articles/Lisacek/description'
import ML from './articles/Mallet_Libert/description'
import MS from './articles/Mansion_Sgro/description'
import SM from './articles/Maurel_Seguy/description'
import OM from './articles/Ory_MaryVallee/description'
import PF from './articles/Pusung_Fan/description'
import RL from './articles/Rathonie_Lienart/description'
import RV from './articles/Rosenberg_Vallet/description'
import Sa from './articles/Sangare/description'
import Se from './articles/Segaux/description'
import Vo from './articles/Vo/description'
import Th from './articles/Thiel/description'
import VV from './articles/Vallee_Veysset/description'

const articlesDescription: Array<ArticleDescription> = [ Edito, BK, BC, BL, CS, CL, DD, Du, DG, Fo, GJ, Ha, HG, KB, La, LL, Li, ML, MS, SM, OM, PF, RL, RV, Sa, Se, Vo, Th, VV ]

export default articlesDescription